export const SCENES = [
  {
    id: 'hero',
    scrollStart: 0.0,
    scrollEnd: 0.18,
    camera: {
      pos: { x: 0.8, y: 2.2, z: 7.0 },
      target: { x: 0.0, y: 0.8, z: 0.0 },
      fov: 52,
    },
    env: {
      fogColor: '#0a1a06',
      fogDensity: 0.018,
      ambientIntensity: 1.0,
      sunIntensity: 2.2,
      skyVisible: true,
      bgColor: '#0d1a09',
    },
    objects: {
      plant: { visible: true, opacity: 1.0 },
      soilSurface: { visible: true, opacity: 1.0 },
      strata: { visible: false, opacity: 0.0 },
      roots: { visible: false, growthProgress: 0.0 },
      mycelium: { visible: false, opacity: 0.0 },
      product: { visible: false, opacity: 0.0 },
    },
  },
  {
    id: 'crossing',
    scrollStart: 0.18,
    scrollEnd: 0.3,
    camera: {
      pos: { x: 0.3, y: -0.5, z: 4.5 },
      target: { x: 0.0, y: -1.5, z: 0.0 },
      fov: 60,
    },
    env: {
      fogColor: '#080e04',
      fogDensity: 0.06,
      ambientIntensity: 0.5,
      sunIntensity: 0.4,
      skyVisible: false,
      bgColor: '#080e04',
    },
    objects: {
      plant: { visible: true, opacity: 0.0 },
      soilSurface: { visible: true, opacity: 1.0 },
      strata: { visible: true, opacity: 0.0 },
      roots: { visible: true, growthProgress: 0.05 },
      mycelium: { visible: false, opacity: 0.0 },
      product: { visible: false, opacity: 0.0 },
    },
  },
  {
    id: 'science',
    scrollStart: 0.3,
    scrollEnd: 0.5,
    camera: {
      pos: { x: 2.0, y: -5.0, z: 4.0 },
      target: { x: 0.0, y: -5.5, z: 0.0 },
      fov: 55,
    },
    env: {
      fogColor: '#060c03',
      fogDensity: 0.04,
      ambientIntensity: 0.3,
      sunIntensity: 0.0,
      skyVisible: false,
      bgColor: '#060c03',
    },
    objects: {
      plant: { visible: false, opacity: 0.0 },
      soilSurface: { visible: false, opacity: 0.0 },
      strata: { visible: true, opacity: 0.8 },
      roots: { visible: true, growthProgress: 0.5 },
      mycelium: { visible: true, opacity: 0.4 },
      product: { visible: false, opacity: 0.0 },
    },
  },
  {
    id: 'howItWorks',
    scrollStart: 0.5,
    scrollEnd: 0.68,
    camera: {
      pos: { x: -1.8, y: -10.0, z: 5.5 },
      target: { x: 0.5, y: -10.5, z: 0.0 },
      fov: 58,
    },
    env: {
      fogColor: '#060c03',
      fogDensity: 0.025,
      ambientIntensity: 0.25,
      sunIntensity: 0.0,
      skyVisible: false,
      bgColor: '#060c03',
    },
    objects: {
      plant: { visible: false, opacity: 0.0 },
      soilSurface: { visible: false, opacity: 0.0 },
      strata: { visible: true, opacity: 0.5 },
      roots: { visible: true, growthProgress: 0.85 },
      mycelium: { visible: true, opacity: 0.9 },
      product: { visible: false, opacity: 0.0 },
    },
  },
  {
    id: 'results',
    scrollStart: 0.68,
    scrollEnd: 0.84,
    camera: {
      pos: { x: 1.5, y: -15.0, z: 5.0 },
      target: { x: 0.0, y: -15.5, z: 0.0 },
      fov: 52,
    },
    env: {
      fogColor: '#060c03',
      fogDensity: 0.015,
      ambientIntensity: 0.2,
      sunIntensity: 0.0,
      skyVisible: false,
      bgColor: '#060c03',
    },
    objects: {
      plant: { visible: false, opacity: 0.0 },
      soilSurface: { visible: false, opacity: 0.0 },
      strata: { visible: true, opacity: 0.3 },
      roots: { visible: true, growthProgress: 1.0 },
      mycelium: { visible: true, opacity: 1.0 },
      product: { visible: true, opacity: 1.0 },
    },
  },
  {
    id: 'buy',
    scrollStart: 0.84,
    scrollEnd: 1.0,
    camera: {
      pos: { x: 0.0, y: -15.0, z: 8.0 },
      target: { x: 0.0, y: -15.5, z: 0.0 },
      fov: 48,
    },
    env: {
      fogColor: '#060c03',
      fogDensity: 0.008,
      ambientIntensity: 0.3,
      sunIntensity: 0.0,
      skyVisible: false,
      bgColor: '#060c03',
    },
    objects: {
      plant: { visible: false, opacity: 0.0 },
      soilSurface: { visible: false, opacity: 0.0 },
      strata: { visible: false, opacity: 0.0 },
      roots: { visible: true, growthProgress: 1.0 },
      mycelium: { visible: true, opacity: 0.7 },
      product: { visible: true, opacity: 1.0 },
    },
  },
]
